spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload & Tomcat limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-parameter-count=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-part-count=1000

# -----------------------------
# ? BOG Payment Configuration
# -----------------------------
# ??????? ??? ??????? ?? ?????????? (???????/???? ??????????)
bog.client.id=10006970
bog.secret.key=yaXeKbffNvK3

# ??? ???? ????????? ?????? ???????????? ???????? ????
# ????????? ???????????? localhost ??????, ?????? gwgtools.ge
#bog.redirect.success.url=http://localhost:8080/payment/success
#bog.redirect.fail.url=http://localhost:8080/payment/fail

bog.redirect.success.url=https://gwgtools.ge/payment/success
bog.redirect.fail.url=https://gwgtools.ge/payment/fail

